repos:
- repo: local
  hooks:
  - id: nose-tests
    name: Run nose tests
    entry: nose2-3
    language: system
    files: '\.py$'
    always_run: true
    pass_filenames: false
    stages: [commit]
- repo: https://github.com/psf/black
  rev: 23.3.0  # Use the specific version of Black you want to run
  hooks:
  - id: black
    language_version: python3.10  # Set the Python version you're using
